#ServerPort
server :
  port : 8090
  
# Datasource Settings
spring:
  datasource:
    driver-class-name : org.postgresql.Driver
    url : jdbc:postgresql://127.0.0.1:5432/hccp
    username : choi


# mybatis config
  mybatis :
    type-aliases-package : co.kr.pine.davinci.dto
    mapper-locations : mapper/**/*.xml

## Logging Set
#  logging :
#    level :
#      root : info
#    file :
#      path : logs

      #logging.level.root = info
      # logging.file.path= logs


## JPA Settings
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto= create
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show-sql=true
##spring.jpa.properties.hibernate.use_sql_comments=true

## logging
#logging.level.org.hibernate.SQL : debug
#logging.level.org.hibernate.type : trace